const STATE_CHANGE = 'STATE_CHANGE';
const ADD_DEVICE = 'ADD_DEVICE';
const REMOVE_DEVICE = 'REMOVE_DEVICE';
const UPDATE_DEVICE = 'UPDATE_DEVICE';

export default {
  STATE_CHANGE,
  ADD_DEVICE,
  REMOVE_DEVICE,
  UPDATE_DEVICE
}