const SET_DEVICE_MONTHS = "SET_DEVICE_MONTHS";
const SET_DEVICE_MONTH = "SET_DEVICE_MONTH";
const SET_ALL_MONTHS = "SET_ALL_MONTHS";

export default {
  SET_DEVICE_MONTHS,
  SET_DEVICE_MONTH,
  SET_ALL_MONTHS
}
